development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: fanhe_test
  pool: 5
  username: root
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: fanhe
  pool: 10
  username: fanbox_dev
  password: zqpm01
  host: rdsm3yuyr26vmqe.mysql.rds.aliyuncs.com